### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by hilmarwenckhepster** [toluaina/pg-sync#39]
Just cloning this repro and run "docker-compose" on MacOS. As far as I understand, it should start an postgresql with sample data and run against it.

Problem Description: start up fails with the following Error message.

Error Message:

```
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-09T12:27:41,668Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "afb2573497b4", "message": "adding index lifecycle policy [slm-history-ilm-policy]", "cluster.uuid": "Wt9naFgLQ7iZkdkyYYHQtw", "node.id": "8cuQXauMTSiIDbOEg8YGkQ"  }
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "examples/airbnb/schema.py", line 130, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "examples/airbnb/schema.py", line 125, in main
pgsync_1         |     teardown(config=config)
pgsync_1         |   File "pgsync/helper.py", line 28, in pgsync.helper.teardown
pgsync_1         |   File "pgsync/sync.py", line 66, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 121, in pgsync.sync.Sync.create_mapping
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-09T12:27:41,779Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "afb2573497b4", "message": "license [f10b15c7-635d-4dfb-a13d-3fd7e2f4d051] mode [basic] - valid", "cluster.uuid": "Wt9naFgLQ7iZkdkyYYHQtw", "node.id": "8cuQXauMTSiIDbOEg8YGkQ"  }
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "examples/airbnb/data.py", line 209, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "examples/airbnb/data.py", line 21, in main
pgsync_1         |     teardown(drop_db=False, config=config)
pgsync_1         |   File "pgsync/helper.py", line 28, in pgsync.helper.teardown
pgsync_1         |   File "pgsync/sync.py", line 66, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 121, in pgsync.sync.Sync.create_mapping
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 63, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/bin/bootstrap", line 54, in main
pgsync_1         |     sync = Sync(document, verbose=verbose, **params)
pgsync_1         |   File "pgsync/sync.py", line 65, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 114, in pgsync.sync.Sync.validate
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync_1         |     sync.main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "pgsync/utils.py", line 69, in pgsync.utils.timeit.timed
pgsync_1         |   File "pgsync/sync.py", line 907, in pgsync.sync.main
pgsync_1         |   File "pgsync/sync.py", line 65, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 114, in pgsync.sync.Sync.validate
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
pg-sync_pgsync_1 exited with code 1

```

**Comment by toluaina** [comment]
You are totally right and this is a regression.
This has been fixed in the latest version 1.1.13. 
Please rebuild with `docker-compose up --force-recreate`

@hilmarwenckhepster

**Comment by hilmarwenckhepster** [comment]
Sadly this did not solve the issue. Here my complete log @toluaina 

`% docker-compose up --force-recreate
Creating network "pg-sync-master_default" with the default driver
Creating pg-sync-master_redis_1         ... done
Creating pg-sync-master_postgres_1      ... done
Creating pg-sync-master_elasticsearch_1 ... done
Creating pg-sync-master_pgsync_1        ... done
Attaching to pg-sync-master_redis_1, pg-sync-master_elasticsearch_1, pg-sync-master_postgres_1, pg-sync-master_pgsync_1
postgres_1       | The files belonging to this database system will be owned by user "postgres".
postgres_1       | This user must also own the server process.
postgres_1       | 
postgres_1       | The database cluster will be initialized with locale "en_US.utf8".
postgres_1       | The default database encoding has accordingly been set to "UTF8".
postgres_1       | The default text search configuration will be set to "english".
postgres_1       | 
postgres_1       | Data page checksums are disabled.
postgres_1       | 
redis_1          | 1:C 10 Sep 2020 07:23:40.078 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 10 Sep 2020 07:23:40.078 # Redis version=6.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 10 Sep 2020 07:23:40.078 # Configuration loaded
postgres_1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
redis_1          | 1:M 10 Sep 2020 07:23:40.079 * Running mode=standalone, port=6379.
redis_1          | 1:M 10 Sep 2020 07:23:40.079 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 10 Sep 2020 07:23:40.079 # Server initialized
redis_1          | 1:M 10 Sep 2020 07:23:40.079 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
postgres_1       | creating subdirectories ... ok
redis_1          | 1:M 10 Sep 2020 07:23:40.079 * Ready to accept connections
postgres_1       | selecting dynamic shared memory implementation ... posix
postgres_1       | selecting default max_connections ... 100
postgres_1       | selecting default shared_buffers ... 128MB
postgres_1       | selecting default time zone ... UTC
postgres_1       | creating configuration files ... ok
postgres_1       | running bootstrap script ... ok
postgres_1       | performing post-bootstrap initialization ... sh: locale: not found
postgres_1       | 2020-09-10 07:23:40.538 GMT [30] WARNING:  no usable system locales were found
pgsync_1         | wait-for-it.sh: waiting 60 seconds for postgres:5432
postgres_1       | ok
postgres_1       | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
postgres_1       | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1       | --auth-local and --auth-host, the next time you run initdb.
postgres_1       | ok
postgres_1       | 
postgres_1       | 
postgres_1       | Success. You can now start the database server using:
postgres_1       | 
postgres_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1       | 
postgres_1       | waiting for server to start....2020-09-10 07:23:40.955 GMT [35] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres_1       | 2020-09-10 07:23:40.956 GMT [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2020-09-10 07:23:40.963 GMT [36] LOG:  database system was shut down at 2020-09-10 07:23:40 GMT
postgres_1       | 2020-09-10 07:23:40.965 GMT [35] LOG:  database system is ready to accept connections
postgres_1       |  done
postgres_1       | server started
postgres_1       | CREATE DATABASE
postgres_1       | 
postgres_1       | 
postgres_1       | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/init-permissions.sh
postgres_1       | 
postgres_1       | 2020-09-10 07:23:41.122 GMT [35] LOG:  received fast shutdown request
postgres_1       | waiting for server to shut down....2020-09-10 07:23:41.123 GMT [35] LOG:  aborting any active transactions
postgres_1       | 2020-09-10 07:23:41.124 GMT [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
postgres_1       | 2020-09-10 07:23:41.124 GMT [37] LOG:  shutting down
postgres_1       | 2020-09-10 07:23:41.129 GMT [35] LOG:  database system is shut down
postgres_1       |  done
postgres_1       | server stopped
postgres_1       | 
postgres_1       | PostgreSQL init process complete; ready for start up.
postgres_1       | 
postgres_1       | 2020-09-10 07:23:41.229 GMT [1] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres_1       | 2020-09-10 07:23:41.229 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1       | 2020-09-10 07:23:41.229 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1       | 2020-09-10 07:23:41.230 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1       | 2020-09-10 07:23:41.237 GMT [46] LOG:  database system was shut down at 2020-09-10 07:23:41 GMT
postgres_1       | 2020-09-10 07:23:41.239 GMT [1] LOG:  database system is ready to accept connections
postgres_1       | 2020-09-10 07:23:41.560 GMT [53] LOG:  incomplete startup packet
pgsync_1         | wait-for-it.sh: postgres:5432 is available after 1 seconds
pgsync_1         | wait-for-it.sh: waiting 60 seconds for elasticsearch:9200
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:42,867Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "using [1] data paths, mounts [[/ (overlay)]], net usable_space [43.8gb], net total_space [58.4gb], types [overlay]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:42,869Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "heap size [1gb], compressed ordinary object pointers [true]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:42,900Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "node name [41856d1b0946], node ID [bCW95oQ4RoK7Co9fmRv3Ag], cluster name [docker-cluster]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:42,902Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "version[7.7.0], pid[7], build[default/docker/81a1e9eda8e6183f5237786246f6dced26a10eaf/2020-05-12T02:01:37.602180Z], OS[Linux/4.19.76-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14/14+36]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:42,903Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "JVM home [/usr/share/elasticsearch/jdk]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:42,903Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-12126464769357689229, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,299Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [aggs-matrix-stats]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,299Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [analysis-common]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,299Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [constant-keyword]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,300Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [flattened]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,300Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [frozen-indices]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [ingest-common]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [ingest-geoip]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,301Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [ingest-user-agent]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [lang-expression]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [lang-mustache]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,302Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [lang-painless]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,303Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [mapper-extras]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,303Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [parent-join]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,304Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [percolator]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,304Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [rank-eval]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,304Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [reindex]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [repository-url]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [search-business-rules]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,305Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [spatial]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [tasks]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [transform]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,306Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [transport-netty4]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [vectors]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-analytics]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,307Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-async-search]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-autoscaling]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-ccr]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,308Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-core]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,309Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-deprecation]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,309Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-enrich]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,309Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-eql]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,310Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-graph]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,310Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-identity-provider]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,310Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-ilm]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,311Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-logstash]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,311Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-ml]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,311Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-monitoring]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,312Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-ql]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,312Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-rollup]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,312Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-security]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,313Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-sql]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,313Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-voting-only-node]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,313Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "loaded module [x-pack-watcher]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:44,314Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "no plugins loaded" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:46,995Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "[controller/204] [Main.cc@110] controller (64 bit): Version 7.7.0 (Build a8939d3da43f33) Copyright (c) 2020 Elasticsearch BV" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:47,445Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "using discovery type [zen] and seed hosts providers [settings]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:48,016Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "initialized" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:48,017Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "starting ..." }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:48,118Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:48,247Z", "level": "WARN", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:48,255Z", "level": "INFO", "component": "o.e.c.c.ClusterBootstrapService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "no discovery configuration found, will perform best-effort cluster bootstrapping after [3s] unless existing master is discovered" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,258Z", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "setting initial configuration to VotingConfiguration{bCW95oQ4RoK7Co9fmRv3Ag}" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,361Z", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "elected-as-master ([1] nodes joined)[{41856d1b0946}{bCW95oQ4RoK7Co9fmRv3Ag}{Ot6j-GF8SKyrGDZeaq1dJQ}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=4131528704, xpack.installed=true, transform.node=true, ml.max_open_jobs=20} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: master node changed {previous [], current [{41856d1b0946}{bCW95oQ4RoK7Co9fmRv3Ag}{Ot6j-GF8SKyrGDZeaq1dJQ}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=4131528704, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]}" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,393Z", "level": "INFO", "component": "o.e.c.c.CoordinationState", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "cluster UUID set to [Vg8beosjSNSUswW0ZLivIA]" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,416Z", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "master node changed {previous [], current [{41856d1b0946}{bCW95oQ4RoK7Co9fmRv3Ag}{Ot6j-GF8SKyrGDZeaq1dJQ}{127.0.0.1}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=4131528704, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]}, term: 1, version: 1, reason: Publication{term=1, version=1}" }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,454Z", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "publish_address {172.22.0.3:9200}, bound_addresses {0.0.0.0:9200}", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,454Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "started", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,529Z", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "recovered [0] indices into cluster_state", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
pgsync_1         | wait-for-it.sh: elasticsearch:9200 is available after 10 seconds
pgsync_1         | wait-for-it.sh: waiting 60 seconds for redis:6379
pgsync_1         | wait-for-it.sh: redis:6379 is available after 0 seconds
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,677Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.watches] for index patterns [.watches*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,738Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.watch-history-11] for index patterns [.watcher-history-11*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,775Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.triggered_watches] for index patterns [.triggered_watches*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,819Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-anomalies-] for index patterns [.ml-anomalies-*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,851Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-state] for index patterns [.ml-state*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,890Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-config] for index patterns [.ml-config]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,921Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-inference-000001] for index patterns [.ml-inference-000001]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,954Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-meta] for index patterns [.ml-meta]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:51,987Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-stats] for index patterns [.ml-stats-*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,019Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.ml-notifications-000001] for index patterns [.ml-notifications-000001]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,056Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [ilm-history] for index patterns [ilm-history-2*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "examples/airbnb/schema.py", line 130, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "examples/airbnb/schema.py", line 125, in main
pgsync_1         |     teardown(config=config)
pgsync_1         |   File "pgsync/helper.py", line 28, in pgsync.helper.teardown
pgsync_1         |   File "pgsync/sync.py", line 66, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 121, in pgsync.sync.Sync.create_mapping
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,094Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.slm-history] for index patterns [.slm-history-2*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,138Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.monitoring-logstash] for index patterns [.monitoring-logstash-7-*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,191Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.monitoring-es] for index patterns [.monitoring-es-7-*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,262Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.monitoring-beats] for index patterns [.monitoring-beats-7-*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,304Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.monitoring-alerts-7] for index patterns [.monitoring-alerts-7]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,339Z", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,367Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding index lifecycle policy [watch-history-ilm-policy]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,401Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding index lifecycle policy [ml-size-based-ilm-policy]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,433Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding index lifecycle policy [ilm-history-ilm-policy]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,460Z", "level": "INFO", "component": "o.e.x.i.a.TransportPutLifecycleAction", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "adding index lifecycle policy [slm-history-ilm-policy]", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "examples/airbnb/data.py", line 209, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "examples/airbnb/data.py", line 21, in main
pgsync_1         |     teardown(drop_db=False, config=config)
pgsync_1         |   File "pgsync/helper.py", line 28, in pgsync.helper.teardown
pgsync_1         |   File "pgsync/sync.py", line 66, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 121, in pgsync.sync.Sync.create_mapping
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
elasticsearch_1  | {"type": "server", "timestamp": "2020-09-10T07:23:52,595Z", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "docker-cluster", "node.name": "41856d1b0946", "message": "license [3476b74c-99f1-431a-a4d6-16796c82166b] mode [basic] - valid", "cluster.uuid": "Vg8beosjSNSUswW0ZLivIA", "node.id": "bCW95oQ4RoK7Co9fmRv3Ag"  }
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/bootstrap", line 63, in <module>
pgsync_1         |     main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "/usr/local/bin/bootstrap", line 54, in main
pgsync_1         |     sync = Sync(document, verbose=verbose, **params)
pgsync_1         |   File "pgsync/sync.py", line 65, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 114, in pgsync.sync.Sync.validate
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
pgsync_1         | Traceback (most recent call last):
pgsync_1         |   File "/usr/local/bin/pgsync", line 7, in <module>
pgsync_1         |     sync.main()
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
pgsync_1         |     return self.main(*args, **kwargs)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
pgsync_1         |     rv = self.invoke(ctx)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
pgsync_1         |     return ctx.invoke(self.callback, **ctx.params)
pgsync_1         |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
pgsync_1         |     return callback(*args, **kwargs)
pgsync_1         |   File "pgsync/utils.py", line 69, in pgsync.utils.timeit.timed
pgsync_1         |   File "pgsync/sync.py", line 907, in pgsync.sync.main
pgsync_1         |   File "pgsync/sync.py", line 65, in pgsync.sync.Sync.__init__
pgsync_1         |   File "pgsync/sync.py", line 114, in pgsync.sync.Sync.validate
pgsync_1         |   File "pgsync/node.py", line 236, in pgsync.node.Tree.build
pgsync_1         |   File "pgsync/base.py", line 110, in pgsync.base.Base.model
pgsync_1         | pgsync.exc.TableNotFoundError: 'Table "public.users" not found in registry'
pg-sync-master_pgsync_1 exited with code 1
`

**Comment by toluaina** [comment]
Sorry you need to rebuild the image
docker-compose build --no-cache 

or better yet 
docker system prune and 
docket-compose up

**Comment by hilmarwenckhepster** [comment]
Thank you. That solved the start issue. Still it is not working:

- `docker-compose up exec -it pgsync` is not a valid command
- You probably mean port 9201, as given in your docker-compose.yml
- When I try to open the page I get following page: `{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [airbnb]","resource.type":"index_or_alias","resource.id":"airbnb","index_uuid":"_na_","index":"airbnb"}],"type":"index_not_found_exception","reason":"no such index [airbnb]","resource.type":"index_or_alias","resource.id":"airbnb","index_uuid":"_na_","index":"airbnb"},"status":404}`


Thanks again for your help.

**Comment by toluaina** [comment]
Sorry, about the misleading doc. 

All you need to do is just `docker-compose up `

I will update the README now.

@hilmarwenckhepster

**Comment by hilmarwenckhepster** [comment]
@toluaina Thank you. I have no rights to create a pull request. But you should edit in the readme the check command to
`$ curl -X GET http://[elasticsearch host]:9201/reservations/_search?pretty=true`

**Comment by toluaina** [comment]
Great thanks for that. I've updated that too

**Comment by toluaina** [comment]
Closing as this has been resolved
